import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CustomNavbar from "../components/CustomNavbar"
import Footer from "../components/Footer"
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import UserProvider from "@/context/userProvider"

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <UserProvider>
          <ToastContainer/>
          <CustomNavbar/>

          <div className="mt-2">{children}</div>

          <Footer/>
        </UserProvider>
      </body>
    </html>
  );
}
